name: Deploy site 

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  deploy:
         name: 'Deploy to Netlify'
         runs-on: ubuntu-latest
         steps:
         - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      
env: 
  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
  index: ${{secrets.index}}
