name: Vercel Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          index: ${{secrets.index}}
        run: npx vercel --token $VERCEL_TOKEN
